# Generated by Django 4.0.4 on 2022-04-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_classname_genus_kingdom_order_phylum_scientificname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='kingdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.kingdom'),
        ),
    ]
