# Generated by Django 4.0.4 on 2022-04-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_image_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_of',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
