# Generated by Django 4.0.4 on 2022-04-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_animal_image_image_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='distint_feature',
            new_name='distinct_feature',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_of',
        ),
    ]
