# Generated by Django 4.0.4 on 2022-05-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_fact_average_litter_size_alter_fact_diet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalcharacteristics',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
