# Generated by Django 4.0.4 on 2022-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_physicalcharacteristics_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
