# Generated by Django 4.0.4 on 2022-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_location_image_animal_locationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='locationimage',
            field=models.ImageField(null=True, upload_to='images/locations/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/animals/'),
        ),
    ]
