# Generated by Django 4.0.4 on 2022-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_family_classification_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='classification_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
