# Generated by Django 4.0.4 on 2022-04-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conservationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='conservation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.conservationstatus'),
        ),
    ]
