# Generated by Django 4.0.4 on 2022-04-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_animal_conservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts_for', models.CharField(blank=True, max_length=50, null=True)),
                ('main_prey', models.CharField(blank=True, max_length=50, null=True)),
                ('distint_feature', models.CharField(blank=True, max_length=50, null=True)),
                ('habitat', models.CharField(blank=True, max_length=50, null=True)),
                ('predators', models.CharField(blank=True, max_length=50, null=True)),
                ('diet', models.CharField(blank=True, max_length=50, null=True)),
                ('average_litter_size', models.CharField(blank=True, max_length=50, null=True)),
                ('lifestyle', models.CharField(blank=True, max_length=50, null=True)),
                ('favourite_food', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('slogan', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='classname',
            options={'verbose_name': 'Class Name'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name_plural': 'Genuses'},
        ),
        migrations.AlterModelOptions(
            name='scientificname',
            options={'verbose_name': 'Scientific Name'},
        ),
        migrations.AddField(
            model_name='animal',
            name='facts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.fact'),
        ),
    ]
