# Generated by Django 4.0.4 on 2022-04-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_location_animal_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='locations',
            new_name='location',
        ),
    ]
