# Generated by Django 4.0.4 on 2022-04-30 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_image_image_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.animal'),
        ),
    ]
