# Generated by Django 4.0.4 on 2022-05-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_distint_feature_fact_distinct_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters_of', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_type', models.CharField(blank=True, max_length=50, null=True)),
                ('top_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('lifespan', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='main_prey',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='predators',
            new_name='group_behavior',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='slogan',
            new_name='name_of_young',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='type',
        ),
        migrations.AddField(
            model_name='fact',
            name='prey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
