# Generated by Django 4.0.4 on 2022-05-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_physicalcharacteristics_rename_main_prey_fact_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='classification_for',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='facts_for',
        ),
        migrations.RemoveField(
            model_name='physicalcharacteristics',
            name='characters_of',
        ),
        migrations.AddField(
            model_name='animal',
            name='physical_characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.physicalcharacteristics'),
        ),
    ]
